export const categories = [
    {
        id: 1,
        name: 'Pizza',
        image: require('../assets/images/categories/icons8-pizza-96.png'),
    },
    {
        id: 2,
        name: 'Burger',
        image: require('../assets/images/categories/icons8-hamburger-96.png'),
    },
    {
        id: 3,
        name: 'Italian',
        image: require('../assets/images/categories/icons8-tropical-fish-96.png'),
    },
    {
        id: 4,
        name: 'Chinese',
        image: require('../assets/images/categories/icons8-takeout-box-96.png'),
    },
    {
        id: 5,
        name: 'Noodles',
        image: require('../assets/images/categories/icons8-spaghetti-96.png'),
    },
    {
        id: 6,
        name: 'Sweets',
        image: require('../assets/images/categories/icons8-cupcake-emoji-96.png'),
    },
];

export const featured2 = {
    id: 2,
    title: 'Sweet',
    description: 'Sweety and yummy',
    restaurants: [
        {
            id: 1,
            name: 'Papa Johns',
            image: require('../assets/images/restaurants/n7yx-hero (1).jpg'),
            description: 'Hot and spicy pizzas',
            lng: 38.2145602,
            lat: -85.5324269,
            address: '434 second street',
            stars: 4,
            reviews: '4.4k',
            category: 'Fast Food',
            dishes: [
                {
                    id: 1,
                    name: 'Pizza',
                    description: 'Cheezy garlic pizza',
                    price: 10,
                    image: require('../assets/images/dishes/images (2).jpeg'),
                },
                {
                    id: 2,
                    name: 'Pizza',
                    description: 'Cheezy garlic pizza',
                    price: 10,
                    image: require('../assets/images/dishes/images (2).jpeg'),
                },
                {
                    id: 3,
                    name: 'Pizza',
                    description: 'Cheezy garlic pizza',
                    price: 10,
                    image: require('../assets/images/dishes/images (2).jpeg'),
                },
            ],
        },
        {
            id: 2,
            name: 'KFC',
            image: require('../assets/images/restaurants/bdcd233971b7c81bf77e1fa4471280eb (1).webp'),
            description: 'Finger lickin good',
            lng: 38.2145602,
            lat: -85.5324269,
            address: 'DHA Phase 4',
            stars: 4,
            reviews: '10.4k',
            category: 'Fast Food',
            dishes: [
                {
                    id: 1,
                    name: 'Pizza',
                    description: 'Cheezy garlic pizza',
                    price: 10,
                    image: require('../assets/images/dishes/images (2).jpeg'),
                },
                {
                    id: 2,
                    name: 'Pizza',
                    description: 'Cheezy garlic pizza',
                    price: 10,
                    image: require('../assets/images/dishes/images (2).jpeg'),
                },
                {
                    id: 3,
                    name: 'Pizza',
                    description: 'Cheezy garlic pizza',
                    price: 10,
                    image: require('../assets/images/dishes/images (2).jpeg'),
                },
            ],
        },
        {
            id: 3,
            name: 'Al-Baiq',
            image: require('../assets/images/restaurants/download (7).jpeg'),
            description: "Saudia's Special Chicken",
            lng: 38.2145602,
            lat: -85.5324269,
            address: 'Cantt Lahore',
            stars: 5,
            reviews: '22.4k',
            category: 'Fast Food',
            dishes: [
                {
                    id: 1,
                    name: 'Pizza',
                    description: 'Cheezy garlic pizza',
                    price: 10,
                    image: require('../assets/images/dishes/images (2).jpeg'),
                },
                {
                    id: 2,
                    name: 'Pizza',
                    description: 'Cheezy garlic pizza',
                    price: 10,
                    image: require('../assets/images/dishes/images (2).jpeg'),
                },
                {
                    id: 3,
                    name: 'Pizza',
                    description: 'Cheezy garlic pizza',
                    price: 10,
                    image: require('../assets/images/dishes/images (2).jpeg'),
                },
            ],
        },  {
            id: 4,
            name: 'Nandos',
            image: require('../assets/images/restaurants/rawImage (1).jpg'),
            description: 'Nand',
            lng: 38.2145602,
            lat: -85.5324269,
            address: 'Gulberg',
            stars: 3.8,
            reviews: '3.4k',
            category: 'Continental',
            dishes: [
                {
                    id: 1,
                    name: 'Pizza',
                    description: 'Cheezy garlic pizza',
                    price: 10,
                    image: require('../assets/images/dishes/images (2).jpeg'),
                },
                {
                    id: 2,
                    name: 'Pizza',
                    description: 'Cheezy garlic pizza',
                    price: 10,
                    image: require('../assets/images/dishes/images (1) (1).jpeg'),
                },
                {
                    id: 3,
                    name: 'Pizza',
                    description: 'Cheezy garlic pizza',
                    price: 10,
                    image: require('../assets/images/dishes/images (2).jpeg'),
                },
            ],
        },
        {
            id: 5,
            name: 'OPTP',
            image: require('../assets/images/restaurants/disadvantages-of-fast-food (1).webp'),
            description: 'One potato two potato',
            lng: 38.2145602,
            lat: -85.5324269,
            address: 'Jail Road',
            stars: 4.8,
            reviews: '13.4k',
            category: 'Fast Food',
            dishes: [
                {
                    id: 1,
                    name: 'Pizza',
                    description: 'Cheezy garlic pizza',
                    price: 10,
                    image: require('../assets/images/dishes/images (2).jpeg'),
                },
                {
                    id: 2,
                    name: 'Pizza',
                    description: 'Cheezy garlic pizza',
                    price: 10,
                    image: require('../assets/images/dishes/images (2).jpeg'),
                },
                {
                    id: 3,
                    name: 'Pizza',
                    description: 'Cheezy garlic pizza',
                    price: 10,
                    image: require('../assets/images/dishes/images (2).jpeg'),
                },
            ],
        },
    ],
    
    
};

export const featured = {
    id: 1,
    title: 'Hot and Spicy',
    description: 'Soft and tender fried chicken',
    restaurants: [
        {
            id: 1,
            name: 'Papa Johns',
            image: require('../assets/images/restaurants/n7yx-hero (1).jpg'),
            description: 'Hot and spicy pizzas',
            lng: 38.2145602,
            lat: -85.5324269,
            address: '434 second street',
            stars: 4,
            reviews: '4.4k',
            category: 'Fast Food',
            dishes: [
                {
                    id: 1,
                    name: 'Pizza',
                    description: 'Cheezy garlic pizza',
                    price: 10,
                    image: require('../assets/images/dishes/images (2).jpeg'),
                },
                {
                    id: 2,
                    name: 'Pizza',
                    description: 'Cheezy garlic pizza',
                    price: 10,
                    image: require('../assets/images/dishes/images (2).jpeg'),
                },
                {
                    id: 3,
                    name: 'Pizza',
                    description: 'Cheezy garlic pizza',
                    price: 10,
                    image: require('../assets/images/dishes/images (2).jpeg'),
                },
            ],
        },
        {
            id: 2,
            name: 'KFC',
            image: require('../assets/images/restaurants/bdcd233971b7c81bf77e1fa4471280eb (1).webp'),
            description: 'Finger lickin good',
            lng: 38.2145602,
            lat: -85.5324269,
            address: 'DHA Phase 4',
            stars: 4,
            reviews: '10.4k',
            category: 'Fast Food',
            dishes: [
                {
                    id: 1,
                    name: 'Pizza',
                    description: 'Cheezy garlic pizza',
                    price: 10,
                    image: require('../assets/images/dishes/images (2).jpeg'),
                },
                {
                    id: 2,
                    name: 'Pizza',
                    description: 'Cheezy garlic pizza',
                    price: 10,
                    image: require('../assets/images/dishes/images (2).jpeg'),
                },
                {
                    id: 3,
                    name: 'Pizza',
                    description: 'Cheezy garlic pizza',
                    price: 10,
                    image: require('../assets/images/dishes/images (2).jpeg'),
                },
            ],
        },
        {
            id: 3,
            name: 'Al-Baiq',
            image: require('../assets/images/restaurants/download (7).jpeg'),
            description: "Saudia's Special Chicken",
            lng: 38.2145602,
            lat: -85.5324269,
            address: 'Cantt Lahore',
            stars: 5,
            reviews: '22.4k',
            category: 'Fast Food',
            dishes: [
                {
                    id: 1,
                    name: 'Pizza',
                    description: 'Cheezy garlic pizza',
                    price: 10,
                    image: require('../assets/images/dishes/images (2).jpeg'),
                },
                {
                    id: 2,
                    name: 'Pizza',
                    description: 'Cheezy garlic pizza',
                    price: 10,
                    image: require('../assets/images/dishes/images (2).jpeg'),
                },
                {
                    id: 3,
                    name: 'Pizza',
                    description: 'Cheezy garlic pizza',
                    price: 10,
                    image: require('../assets/images/dishes/images (2).jpeg'),
                },
            ],
        },  {
            id: 4,
            name: 'Nandos',
            image: require('../assets/images/restaurants/rawImage (1).jpg'),
            description: 'Nand',
            lng: 38.2145602,
            lat: -85.5324269,
            address: 'Gulberg',
            stars: 3.8,
            reviews: '3.4k',
            category: 'Continental',
            dishes: [
                {
                    id: 1,
                    name: 'Pizza',
                    description: 'Cheezy garlic pizza',
                    price: 10,
                    image: require('../assets/images/dishes/images (2).jpeg'),
                },
                {
                    id: 2,
                    name: 'Pizza',
                    description: 'Cheezy garlic pizza',
                    price: 10,
                    image: require('../assets/images/dishes/images (2).jpeg'),
                },
                {
                    id: 3,
                    name: 'Pizza',
                    description: 'Cheezy garlic pizza',
                    price: 10,
                    image: require('../assets/images/dishes/images (2).jpeg'),
                },
            ],
        },
        {
            id: 5,
            name: 'OPTP',
            image: require('../assets/images/restaurants/disadvantages-of-fast-food (1).webp'),
            description: 'One potato two potato',
            lng: 38.2145602,
            lat: -85.5324269,
            address: 'Jail Road',
            stars: 4.8,
            reviews: '13.4k',
            category: 'Fast Food',
            dishes: [
                {
                    id: 1,
                    name: 'Pizza',
                    description: 'Cheezy garlic pizza',
                    price: 10,
                    image: require('../assets/images/dishes/images (2).jpeg'),
                },
                {
                    id: 2,
                    name: 'Pizza',
                    description: 'Cheezy garlic pizza',
                    price: 10,
                    image: require('../assets/images/dishes/images (2).jpeg'),
                },
                {
                    id: 3,
                    name: 'Pizza',
                    description: 'Cheezy garlic pizza',
                    price: 10,
                    image: require('../assets/images/dishes/images (2).jpeg'),
                },
            ],
        },
    ],
    
    
};
